### ISSUE TITLE
Could not read page 0x00000000

### ISSUE THREAD

**Issue by Dishendramishra** [nfd/spi-flash-programmer#14]
I programmed Nodemcu with your sketch and I was checking whether it is working or not.
I change SPI pins for nodemcu accordingly (https://www.electronicwings.com/nodemcu/nodemcu-spi-with-arduino-ide).

When I try to read and write from a winbond 25q128fvsg, it shows the following errors.

![Screenshot_2019-05-03_12-33-49](https://user-images.githubusercontent.com/6905938/57123683-49b05a80-6da0-11e9-9044-0bbafa55acbb.png)

I thought it might be an issue with loose dupont wires. I double checked them but it didn't help. 

Error while trying to write.
![new](https://user-images.githubusercontent.com/6905938/57123867-191cf080-6da1-11e9-9d32-69912eb883ff.png)

**Comment by userid0x0** [comment]
Hi, did you try reading the id and status register already?
Client arguments
id-register and status-register

**Comment by Dishendramishra** [comment]
@userid0x0 
![status](https://user-images.githubusercontent.com/6905938/57144420-acc0e200-6dde-11e9-85ca-f87199229450.png)

I think these register values should remain the same instead of varying. Isn't it?

**Comment by Dishendramishra** [comment]
![1](https://user-images.githubusercontent.com/6905938/57151007-73dc3980-6ded-11e9-81dd-cf20e5c78384.png)
It was a faulty usb cable.

**Comment by userid0x0** [comment]
Definitely. I have no experience values with nodemcu/ESPxxxx sorry.
It's always recommend to start with reading the id-register.
