### ISSUE TITLE
Thank you contributers. I can recover my router. 

### ISSUE THREAD

**Issue by tomudo** [nfd/spi-flash-programmer#22]
My router is TP-Link Archer vr1200v  [http://en.techinfodepot.shoutwiki.com/wiki/TP-LINK_Archer_VR1200v] which has little info about this router on internet. I update wrong firmware version which rendered router to be bricked. 

I upload Wemos D1 (esp8266) to program correct firmware on 25q127csig eeprom and it work like a magic.

**Comment by nfd** [comment]
Such a nice outcome! Thanks for the report and I'm really glad the project could help.
